#!/usr/bin/env sh

stow -t ~ \
  X \
  alacritty \
  bash \
  compton \
  dunst \
  emacs \
  i3 \
  i3status \
  nvim \
  starship \
  tmux \
  zathura \
  zsh

sudo stow -t / \
    debian

./spotify

