#!/usr/bin/env bash

# MISC

super + Return
    $TERMINAL
super + shift + Return
    floating-term
super + d
    rofi -show run
super + shift + d
    desktops
uper + w
    $BROWSER
super + 0
    /home/matte/.cargo/bin/xcursorlocate
super + shift + s
    flameshot gui
super + BackSpace
    poweroff-menu
super + shift + c
    xcolor | tr -d '\n' | xsel -ib
super + x
    command -v slock && (slock & xset dpms force off)
super + shift + t
    telegram-desktop
# Reload sxhkd
super + Escape
    pkill -USR1 -x sxhkd


# X KEYS

XF86PowerOff
    prompt "Shutdown computer?" "systemctl poweroff"
XF86Calculator
    $TERMINAL -e insect
XF86Sleep
    prompt "Suspend computer?" "systemctl suspend"
XF86WWW
    $BROWSER
XF86DOS
    $TERMINAL
XF86ScreenSaver
    slock; xset dpms force off
XF86TaskPane
    $TERMINAL -e htop
XF86MonBrightness{Down,Up}
    xbacklight -{dec,inc} 5
XF86Audio{Raise,Lower}Volume
    vol{up,down}
XF86Audio{_,Mic}Mute
    {vol,mic}toggle
XF86Audio{Prev,Play,Next}
    playerctl {previous,play-pause,next}


# BSPWM HOTKEYS

# Quit / restart bspwm
super + shift + {q,r}
    bspc {quit,wm -r}
# Close and kill
super + q
    bspc node -c
# Alternate between the tiled and monocle layout
super + m
    bspc desktop -l next
# Send the newest marked node to the newest preselected node
super + y
    bspc node newest.marked.local -n newest.!automatic.local
# Swap the current node and the biggest node
super + g
    bspc node -s biggest


# STATE / FLAGS

# Set the window state
super + {t,shift + t,s,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}
# Set the node flags
super + ctrl + {m,x,y,z}
    bspc node -g {marked,locked,sticky,private}


# FOCUS / SWAP

# Focus the node in the given direction
super + {_,shift + }{h,j,k,l}
    bspc node -{f,s} {west,south,north,east}
# Focus the node for the given path jump
super + {p,b,comma,period}
    bspc node -f @{parent,brother,first,second}
# Focus the next/previous node in the current desktop
super + {_,shift + }n
    bspc node -f {next,prev}.local
# Focus the next/previous desktop in the current monitor
super + {minus,equal}
    bspc desktop -f {prev,next}.local
# Focus the last node/desktop
super + {grave,Tab}
    bspc {node,desktop} -f last
# Focus the older or newer node in the focus history
super + {o,i}
    bspc wm -h off; \
    bspc node {older,newer} -f; \
    bspc wm -h on
# Focus or send to the given desktop
super + {_,shift + {1-9}}
    bspc {desktop -f,node -d} focused:'^{1-9}'


# PRESELECT

# Preselect the direction
super + ctrl + {h,j,k,l}
    bspc node -p {west,south,north,east}
# Preselect the ratio
super + ctrl + {1-9}
    bspc node -o 0.{1-9}
# Cancel the preselection for the focused node
super + ctrl + space
    bspc node -p cancel
# Cancel the preselection for the focused desktop
super + ctrl + shift + space
    bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel


# MOVE / RESIZE

# Expand a window by moving one of its side outward
super + alt + {h,j,k,l}
    bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}
# Contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
    bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}
# Move a floating window
super + {Left,Down,Up,Right}
    bspc node -v {-20 0,0 20,0 -20,20 0}

