default_flags = "ig"

[[verbs]]
invocation = "edit"
key = "F2"
shortcut = "e"
execution = "$EDITOR {file}"

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
execution = "git diff {file}"

[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"

[[verbs]]
key = "left"
execution = ":parent"

[[verbs]]
key = "right"
execution = ":focus"

[[verbs]]
key = "ctrl-j"
execution = ":line_down"

[[verbs]]
key = "ctrl-k"
execution = ":line_up"

[[verbs]]
key = "ctrl-d"
execution = ":page_down"

[[verbs]]
key = "ctrl-u"
execution = ":page_up"

[[verbs]]
key = "ctrl-g"
execution = ":toggle_git_status"

[skin]
default = "ansi(7) ansi(0)"
tree = "gray(8) none"
file = "ansi(7) none"
directory = "ansi(4) none bold"
exe = "ansi(6) none"
link = "ansi(5) none"
pruning = "gray(8) none Italic"
# sparse = "ansi(214) none"
perm__ = "gray(8) none bold"
perm_r = "ansi(3) none bold"
perm_w = "ansi(1) none bold"
perm_x = "ansi(2) none bold"
selected_line = "none gray(5)"
char_match = "ansi(3) none bold"
# file_error = "red none"
# flag_label = "gray(16) none"
# flag_value = "rgb(255, 152, 0) none bold"
# Cursor
input = "ansi(7) none"
status_error = "red none"
# status_job = "ansi(220) gray(5)"
status_normal = "ansi(7) none"
status_italic = "ansi(3) none bold"
# status_bold = "rgb(255, 152, 0) gray(3) bold"
# status_code = "ansi(229) gray(5)"
# status_ellipsis = "gray(19) gray(1)"
scrollbar_track = "gray(5) none"
scrollbar_thumb = "ansi(7) none"
help_paragraph = "ansi(8) none"
help_bold = "ansi(7) none bold"
help_italic = "ansi(7) none italic"
help_code = "ansi(7) gray(3)"
help_headers = "ansi(6) none"

