#!/usr/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up
bspc rule -r "*"

# bspc config border_radius 8
bspc config border_width 2
bspc config window_gap 0
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config single_monocle false
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#282828"
bspc config active_border_color "#7c6f64"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#ebdbb2"

# Polybar hidden when fullscreen for vlc, youtube, mpv...
# Find out the name of your monitor with xrandr and name of polybar instance
# with xwininfo
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Screenkey manage=off
bspc rule -a Chromium desktop='^2'

bspc monitor -d 1 2 3 4 5 6 7 8 9
# bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9
# bspc desktop -f 1 2 3 4 5 6 7 8 9

