#!/usr/bin/env dash

# If refreshing bspwm, remove all previous rules to prevent doubling up
bspc rule -r "*"

bspc config border_width 1
bspc config window_gap 0
bspc config top_padding 0
bspc config bottom_padding 43
bspc config left_padding 0
bspc config right_padding 0
bspc config single_monocle true
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#282828"
bspc config active_border_color "#282828"
bspc config focused_border_color "#504945"
bspc config presel_feedback_color "#504945"

bspc config external_rules_command "${HOME}/.config/bspwm/external_rules"

# bspc rule -a Blueman-manager state=floating center=true
# bspc rule -a Pcmanfm state=floating center=true
# bspc rule -a Gdmap state=floating center=true
# bspc rule -a Xarchiver state=floating center=true
# bspc rule -a Pavucontrol state=floating center=true
# bspc rule -a Arandr state=floating center=true
bspc rule -a Emacs state=tiled
bspc rule -a AlacrittyFloating state=floating center=true

bspc monitor -d uno due tre quattro cinque sei sette otto nove

