eval %sh{
    files="
        commands.kak
        mappings.kak
        core.kak
        langs.kak
        filetype/mod.kak
    "

    for file in ${files}; do
        printf '%s\n' "
            try %{
                source %{${kak_config}/${file}}
            } catch %{
                echo -debug %val{error}
            }
        "
    done
}

